### ISSUE TITLE
Dont store snippets on server

### ISSUE THREAD

**Issue by markknol** [clemos/try-haxe#111]
We could store the complete snippet and settings in the url, like [this markdown editor](http://jbt.github.io/markdown-editor/) does.

There is a potential issue if any of the snippets contains sensitive info and one starts guessing the hashes. If the content is in the url then its up to the user to share it.

**Comment by clemos** [comment]
I think both solutions have their pros and cons, including their own security issues.
In any case, it's obviously not recommended to put "sensitive info" in try haxe snippets, as it is not designed for privacy at all ;)

This said, the feature would be nice to have for easily embedding code: https://github.com/clemos/try-haxe/issues/48

**Comment by TuukkaX** [comment]
As far as I understand, guessing is not the biggest issue, since one is able to generate URLs, visit them, and save every snippet where the code in the text box is not the default code seen on the site.

The URLs will get very large, quickly. However, this is not a problem on many places, and besides, URL shortening can be done manually by the user (not sure if URL shorteners allow certain companies do this automatically).
