### ISSUE TITLE
Updating libraries

### ISSUE THREAD

**Issue by back2dos** [clemos/try-haxe#138]
What's the process for updating libraries? In particular I would like very much to have tink_core be updated ;)

**Comment by clemos** [comment]
Currently, I have to update / install the compiler and libraries "by hand" on the server.
I'll make sure it gets updated along with #137, which I might have time to do this week-end.

**Comment by clemos** [comment]
I updated all libraries right after #137 :)

**Comment by back2dos** [comment]
Thanks :)

**Comment by gene-pavlovsky** [comment]
Maybe set up a cron-job to update the libs daily/weekly?

**Comment by markknol** [comment]
That could break compatibility with older snippets, not sure if that is a concern.

**Comment by gene-pavlovsky** [comment]
Adapt or die ;)

On 30 Nov 2017 13:58, "Mark Knol" <notifications@github.com> wrote:

That could break compatibility with older snippets, not sure if that is a
concern.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/clemos/try-haxe/issues/138#issuecomment-348181024>, or mute
the thread

**Comment by back2dos** [comment]
Well, you cannot modify existing snippets anymore, so there is no way to adapt.

**Comment by gene-pavlovsky** [comment]
I see a feature request right there
