### ISSUE TITLE
"Simple" mode

### ISSUE THREAD

**Issue by fullofcaffeine** [clemos/try-haxe#92]
Would it make sense to have a simple mode that would hide the `Test` class declaration and the `main` entry point?

**Comment by clemos** [comment]
It's funny, because most people would rather want multiple files support :p 
(see https://github.com/clemos/try-haxe/issues/65)

I think there was a Haxe REPL project, somewhere (not related to Haxe),
possibly with a web interface,
but I can't seem to find it anymore.

In any case, I don't think it's a good idea to add this "simple mode", 
because it wouldn't be so simple to implement, for instance in the UI, but also in the backend ( the code should be wrapped in a class anyway, and then error messages, completion points, should be converted back and forth, ... ).

**Comment by clemos** [comment]
For the record, there's https://bitbucket.org/yar3333/haxe-haxescript

**Comment by anissen** [comment]
Another alternative is [DConsole](https://github.com/tiagolr/dconsole), which also has [a web interface](http://tiagolr.github.io/dconsole/) that simply allows for executing [hscript](https://github.com/HaxeFoundation/hscript) code directly in the browser.

**Comment by clemos** [comment]
Right, that's what I was looking for :)

**Comment by clemos** [comment]
Not sure it would be interesting to add to try-haxe, as it really demonstrates hscript features, not Haxe.
